// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EffectsController from "./effects_controller"
import FormsController from "./forms_controller"
import ManageUserController from "./manage_user_controller"
import EnrollModal from "./enroll_modal"
import RecordsTable from "./records_table_controller"
import ModalController from "./modal_controller"
import SyncsController from "./syncs_controller"
import ManageEvaluationController from "./manage_evaluation_controller"
application.register("effects", EffectsController)
application.register("forms",FormsController)
application.register("manage-user",ManageUserController)
application.register("enroll-modal",EnrollModal)
application.register("records-table", RecordsTable)
application.register("modal",ModalController)
application.register("sync",SyncsController)
application.register("manage-evaluation",ManageEvaluationController)
